### ISSUE TITLE
500 Server Error for HTTP GET "/swagger-ui.html"

### ISSUE THREAD

**Issue by kchvilyov** [jaggerwang/spring-boot-in-practice#1]
Started by "By docker compose".
http://localhost:8080/ opened successfully.
But http://localhost:8080/swagger-ui.html returns "[b9880223] There was an unexpected error (type=Internal Server Error, status=500).
The mapper returned a null value."
Docker log: "a.w.r.e.AbstractErrorWebExceptionHandler : [b9880223] 500 Server Error for HTTP GET "/swagger-ui.html"
How can I fix this error?

|_ checkpoint ⇢ HTTP GET "/swagger-ui.html" [ExceptionHandlingWebHandler]"

**Comment by jaggerwang** [comment]
Does there have any error logs on server console?

**Comment by kchvilyov** [comment]
Sorry. I can't look now. May be later..

**Comment by kchvilyov** [comment]
Sorry, I found this error in spring-cloud-in-practice.
I have created correct issue here: https://github.com/jaggerwang/spring-cloud-in-practice/issues/3
