### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by zhanglolo** [jaggerwang/spring-boot-in-practice#2]
在usecase层定义的dao接口中某个查询方法，返回的结果要做分页的话，那这个类会使用到其他框架的page和sort类。

这样的话就不符合向内依赖。

遇到这样的场景，应该怎么解决呢。

**Comment by jaggerwang** [comment]
可以使用简单的 offset、limit 方式，或者自己封装 Page 和 Sort 工具类。也不是说完全绝对就不依赖其它框架里的任何东西，比如说一些工具类，只要对后期的可替换性影响不大，也可以使用（到时可引入最小包而不是整个框架）。

**Comment by zhanglolo** [comment]
感谢答疑～
有点过于陷入原则，纠结太久了。
